const refs = {
  loginElem: document.querySelector(".login"),
  loginForm: document.querySelector(".login-form"),
  emailInput: document.querySelector(".login-email"),
  passwordInput: document.querySelector(".login-password"),
  loginSingUplink: document.querySelector(".login-singup"),
  userElem: document.querySelector('.user'),
  userName: document.querySelector('.user-name'),
  exitElem: document.querySelector('.exit'),
  editElem: document.querySelector('.edit'),
  editConteiner: document.querySelector('.edit-conteiner'),
  editUserName: document.querySelector('.edit-username'),
  editFotoURL: document.querySelector('.edit-photo'),
  userAvatar: document.querySelector('.user-avatar'),
  postsWrapper: document.querySelector('.posts'),
  btnNewPost: document.querySelector('.button-new-post'),
  addPostElem: document.querySelector('.add-post'),
  loginForget:document.querySelector('.login-forget'),
};
export default refs
